name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Buildozer
        run: pip install buildozer cython==0.29.33
      - name: Build
        run: |
          buildozer init
          buildozer android debug
